# EventConsumerApp Configuration

# Threading Configuration
consumer.threads=9

# Message Consumption Configuration
consumer.receive.timeout.ms=1000

# Queue and Subscriber Configurations
# Action Updates
consumer.action.queue=ActionUpdatesTopic
consumer.action.subscriber=ActionUpdatesSubscriber1

# Payment Updates
consumer.payment.queue=PaymentUpdatesTopic
consumer.payment.subscriber=PaymentUpdatesSubscriber1

# Statement Updates
consumer.statement.queue=TransactionStatementTopic
consumer.statement.subscriber=StatementsUpdatesSubscriber1

# Consumer retry and error handling
consumer.error.retry.delay.seconds=2
consumer.shutdown.timeout.seconds=10
